const styles = theme =>(
  {
  filters:{
    display:'flex',
    width:'100%',
    flexWrap:'wrap',
    boxSizing:'border-box',
    padding:'15px'
  },
  entry:{
    width:'90%',
    boxSizing:'inherit',
    display:'flex',
    [theme.breakpoints.up('sm')]:{
      width:'45%'
    },
    [theme.breakpoints.up('md')]:{
      width:'23%'
    }
  },
  button:{
    alignSelf:'center'
  },
  tableWrapper:{
    marginTop:'15px',
  },
  chart:{
    width:'100%',
    padding:'8px',
    boxSizing:'border-box',
    overflowX:'auto',
  },
}
)
export default styles
